"""
SVG identity card generation for persona visualization and export.
"""
import logging
from typing import Optional
from models import AestheticResponse

logger = logging.getLogger(__name__)


class IdentityCardGenerator:
    """Generates SVG identity cards for personas."""

    @staticmethod
    def generate_card_svg(
        persona: AestheticResponse,
        image_url: Optional[str] = None
    ) -> str:
        """
        Generate SVG identity card for persona.
        
        Args:
            persona: AestheticResponse object
            image_url: Optional background image URL
            
        Returns:
            SVG string
        """
        try:
            # Escape special characters for SVG
            identity = persona.aesthetic_identity.replace("&", "&amp;").replace("<", "&lt;")
            vibe = persona.vibe_description.replace("&", "&amp;").replace("<", "&lt;")

            # Format traits
            traits_text = " • ".join(persona.traits)
            traits_text = traits_text.replace("&", "&amp;").replace("<", "&lt;")

            # Format routine
            routine_items = "\n".join([f"✧ {step}" for step in persona.routine])
            routine_items = routine_items.replace("&", "&amp;").replace("<", "&lt;")

            svg = f"""<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 800" width="600" height="800">
  <!-- Background -->
  <defs>
    <linearGradient id="bgGradient" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#f5e6d3;stop-opacity:1" />
      <stop offset="100%" style="stop-color:#e8cfc4;stop-opacity:1" />
    </linearGradient>
    <linearGradient id="accentGradient" x1="0%" y1="0%" x2="0%" y2="100%">
      <stop offset="0%" style="stop-color:#d4a5a5;stop-opacity:0.3" />
      <stop offset="100%" style="stop-color:#e8d5d5;stop-opacity:0.3" />
    </linearGradient>
  </defs>

  <!-- Main background -->
  <rect width="600" height="800" fill="url(#bgGradient)"/>

  <!-- Decorative header -->
  <rect x="0" y="0" width="600" height="120" fill="url(#accentGradient)"/>
  <text x="50" y="50" font-family="Georgia, serif" font-size="14" fill="#999" letter-spacing="3">
    ✨ AESTHETIC ALTER EGO ✨
  </text>

  <!-- Identity name (main focus) -->
  <text x="50" y="100" font-family="Georgia, serif" font-size="36" font-weight="bold" fill="#3d3d3d">
    {identity}
  </text>

  <!-- Vibe description -->
  <text x="50" y="160" font-family="Georgia, serif" font-size="16" fill="#666" font-style="italic">
    "{vibe}"
  </text>

  <!-- Section: Traits -->
  <text x="50" y="220" font-family="Georgia, serif" font-size="12" fill="#999" letter-spacing="2" font-weight="bold">
    PERSONALITY TRAITS
  </text>
  <text x="50" y="250" font-family="Georgia, serif" font-size="14" fill="#4d4d4d">
    {traits_text}
  </text>

  <!-- Section: Daily Routine -->
  <text x="50" y="310" font-family="Georgia, serif" font-size="12" fill="#999" letter-spacing="2" font-weight="bold">
    AESTHETIC ROUTINE
  </text>
  <text x="50" y="340" font-family="Georgia, serif" font-size="13" fill="#4d4d4d" line-height="1.8">
    {routine_items}
  </text>

  <!-- Section: Spotify Playlist -->
  <text x="50" y="540" font-family="Georgia, serif" font-size="12" fill="#999" letter-spacing="2" font-weight="bold">
    SOUNDTRACK
  </text>
  <text x="50" y="570" font-family="Georgia, serif" font-size="16" fill="#5d5d5d" font-weight="500">
    {persona.spotify_playlist}
  </text>

  <!-- Footer -->
  <text x="50" y="750" font-family="Georgia, serif" font-size="11" fill="#aaa">
    Generated by Muse.me ✨
  </text>
  <text x="50" y="770" font-family="Georgia, serif" font-size="11" fill="#aaa">
    Your life, romanticized by AI
  </text>

  <!-- Decorative elements -->
  <circle cx="580" cy="50" r="8" fill="#d4a5a5" opacity="0.5"/>
  <circle cx="30" cy="780" r="6" fill="#d4a5a5" opacity="0.5"/>
  <line x1="50" y1="580" x2="550" y2="580" stroke="#d4a5a5" stroke-width="1" opacity="0.3"/>
</svg>"""

            logger.info("Generated SVG identity card")
            return svg

        except Exception as e:
            logger.error(f"Failed to generate identity card: {str(e)}")
            raise

    @staticmethod
    def generate_html_card(
        persona: AestheticResponse,
        image_url: Optional[str] = None
    ) -> str:
        """
        Generate HTML version of identity card for web display.
        
        Args:
            persona: AestheticResponse object
            image_url: Optional background image URL
            
        Returns:
            HTML string
        """
        traits_html = "".join([f"<span class='trait'>{t}</span>" for t in persona.traits])
        routine_html = "".join([f"<div class='routine-step'>✧ {step}</div>" for step in persona.routine])

        html = f"""
<div class="persona-card">
  <div class="card-header">
    <div class="card-label">✨ AESTHETIC ALTER EGO ✨</div>
  </div>
  
  <div class="card-content">
    <h1 class="persona-identity">{persona.aesthetic_identity}</h1>
    
    <p class="vibe-description">"{persona.vibe_description}"</p>
    
    <div class="traits-section">
      <h3>PERSONALITY TRAITS</h3>
      <div class="traits-container">{traits_html}</div>
    </div>
    
    <div class="routine-section">
      <h3>AESTHETIC ROUTINE</h3>
      <div class="routine-container">{routine_html}</div>
    </div>
    
    <div class="spotify-section">
      <h3>SOUNDTRACK</h3>
      <p class="playlist-name">{persona.spotify_playlist}</p>
    </div>
  </div>
  
  <div class="card-footer">
    <p>Generated by Muse.me ✨</p>
    <p>Your life, romanticized by AI</p>
  </div>
</div>
"""
        logger.info("Generated HTML identity card")
        return html
