import React, { useRef } from 'react';
import { motion } from 'framer-motion';
import html2canvas from 'html2canvas';

export default function PersonaCard({ persona }) {
  const cardRef = useRef(null);

  const downloadCard = async (format = 'png') => {
    if (!cardRef.current) return;

    try {
      const canvas = await html2canvas(cardRef.current, {
        backgroundColor: '#f5e6d3',
        scale: 2,
      });

      const link = document.createElement('a');
      link.href = canvas.toDataURL(`image/${format}`);
      link.download = `${persona.persona.aesthetic_identity.replace(/\s+/g, '_')}.${format}`;
      link.click();
    } catch (error) {
      console.error('Error downloading card:', error);
    }
  };

  const containerVariants = {
    hidden: { opacity: 0, scale: 0.95 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: { duration: 0.6 },
    },
  };

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="space-y-8"
    >
      {/* Card Display */}
      <motion.div
        ref={cardRef}
        className="bg-muse-cream rounded-xl shadow-2xl p-12 max-w-2xl mx-auto"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        {/* Header */}
        <div className="text-center mb-8 pb-6 border-b-2 border-muse-rose opacity-50">
          <p className="text-sm font-serif text-gray-500 tracking-widest mb-4">
            ✨ AESTHETIC ALTER EGO ✨
          </p>
        </div>

        {/* Identity Name */}
        <h2 className="text-5xl font-serif font-bold text-muse-dark text-center mb-6">
          {persona.persona.aesthetic_identity}
        </h2>

        {/* Vibe Description */}
        <p className="text-xl text-muse-rose text-center font-serif italic mb-8">
          "{persona.persona.vibe_description}"
        </p>

        {/* Traits */}
        <div className="mb-8">
          <h3 className="text-sm font-serif font-bold text-gray-500 tracking-widest mb-4">
            PERSONALITY TRAITS
          </h3>
          <div className="flex flex-wrap gap-2 justify-center">
            {persona.persona.traits.map((trait, idx) => (
              <motion.span
                key={idx}
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.1 + idx * 0.05 }}
                className="bg-muse-rose bg-opacity-20 text-muse-dark px-4 py-2 rounded-full font-serif text-sm"
              >
                {trait}
              </motion.span>
            ))}
          </div>
        </div>

        {/* Routine */}
        <div className="mb-8">
          <h3 className="text-sm font-serif font-bold text-gray-500 tracking-widest mb-4">
            AESTHETIC ROUTINE
          </h3>
          <div className="space-y-3">
            {persona.persona.routine.map((step, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.15 + idx * 0.05 }}
                className="flex items-start gap-3"
              >
                <span className="text-muse-rose font-serif">✧</span>
                <p className="font-serif text-gray-800">{step}</p>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Spotify Playlist */}
        <div className="bg-muse-dark bg-opacity-5 rounded-lg p-6 text-center">
          <p className="text-xs font-serif text-gray-500 tracking-widest mb-2">🎵 SOUNDTRACK</p>
          <p className="text-2xl font-serif font-bold text-muse-dark">
            {persona.persona.spotify_playlist}
          </p>
        </div>

        {/* Footer */}
        <div className="text-center mt-8 pt-6 border-t-2 border-muse-rose opacity-50">
          <p className="text-xs font-serif text-gray-500">
            Generated by Muse.me ✨ • Your life, romanticized by AI
          </p>
        </div>
      </motion.div>

      {/* Moodboard Prompts */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4 }}
        className="bg-white rounded-xl shadow-lg p-8 max-w-2xl mx-auto"
      >
        <h3 className="text-2xl font-serif font-bold text-muse-dark mb-6">
          🎨 Moodboard Prompts for Your Aesthetic
        </h3>
        <div className="space-y-4">
          {persona.persona.moodboard_prompts.map((prompt, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.45 + idx * 0.05 }}
              className="bg-gradient-to-r from-muse-cream to-transparent p-4 rounded-lg border-l-4 border-muse-rose"
            >
              <p className="font-serif text-gray-800">{prompt}</p>
            </motion.div>
          ))}
        </div>
      </motion.div>

      {/* Spotify Info */}
      {persona.spotify_link && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
          className="bg-green-50 rounded-xl shadow-lg p-8 max-w-2xl mx-auto text-center"
        >
          <h3 className="text-2xl font-serif font-bold text-gray-800 mb-4">
            🎵 Discover Your Soundtrack on Spotify
          </h3>
          <a
            href={persona.spotify_link}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-block px-8 py-3 bg-green-500 text-white rounded-full font-serif font-bold hover:bg-green-600 transition-colors"
          >
            Open on Spotify →
          </a>
        </motion.div>
      )}

      {/* Download Options */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.6 }}
        className="flex flex-col sm:flex-row gap-4 justify-center max-w-2xl mx-auto"
      >
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          onClick={() => downloadCard('png')}
          className="px-8 py-3 bg-muse-rose text-white rounded-full font-serif font-bold hover:shadow-lg transition-shadow"
        >
          📥 Download as PNG
        </motion.button>
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          onClick={() => downloadCard('png')}
          className="px-8 py-3 bg-muse-dark text-white rounded-full font-serif font-bold hover:shadow-lg transition-shadow"
        >
          🎨 Share This Card
        </motion.button>
      </motion.div>
    </motion.div>
  );
}
