/**
 * Generate SVG identity card
 */
export function generateCardSVG(persona) {
  const colors = persona.color_palette || ['#E8C4C4', '#D4A5A5', '#B88E8E'];
  
  const svg = `
<svg width="800" height="1200" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bgGradient" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:${colors[0]};stop-opacity:1" />
      <stop offset="50%" style="stop-color:${colors[1]};stop-opacity:1" />
      <stop offset="100%" style="stop-color:${colors[2]};stop-opacity:1" />
    </linearGradient>
    <filter id="glow">
      <feGaussianBlur stdDeviation="4" result="coloredBlur"/>
      <feMerge>
        <feMergeNode in="coloredBlur"/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
  </defs>
  
  <!-- Background -->
  <rect width="800" height="1200" fill="url(#bgGradient)" />
  
  <!-- Border frame -->
  <rect x="30" y="30" width="740" height="1140" fill="none" stroke="#ffffff" stroke-width="2" opacity="0.6" />
  <rect x="40" y="40" width="720" height="1120" fill="none" stroke="#ffffff" stroke-width="1" opacity="0.4" />
  
  <!-- Title -->
  <text x="400" y="120" font-family="Georgia, serif" font-size="48" fill="#ffffff" text-anchor="middle" filter="url(#glow)" font-weight="bold">
    ${escapeXml(persona.aesthetic_identity)}
  </text>
  
  <!-- Subtitle -->
  <text x="400" y="170" font-family="Georgia, serif" font-size="20" fill="#ffffff" text-anchor="middle" opacity="0.9" font-style="italic">
    ${escapeXml(persona.aesthetic_subtitle)}
  </text>
  
  <!-- Divider -->
  <line x1="100" y1="220" x2="700" y2="220" stroke="#ffffff" stroke-width="1" opacity="0.5" />
  
  <!-- Personality Traits -->
  <text x="400" y="280" font-family="Georgia, serif" font-size="24" fill="#ffffff" text-anchor="middle" font-weight="bold">
    ✦ Personality Traits ✦
  </text>
  ${persona.persona_traits.map((trait, i) => `
  <text x="400" y="${320 + i * 35}" font-family="Arial, sans-serif" font-size="18" fill="#ffffff" text-anchor="middle" opacity="0.95">
    ${escapeXml(trait)}
  </text>
  `).join('')}
  
  <!-- Vibe Description -->
  <text x="400" y="${380 + persona.persona_traits.length * 35}" font-family="Georgia, serif" font-size="24" fill="#ffffff" text-anchor="middle" font-weight="bold">
    ✦ Essence ✦
  </text>
  ${wrapText(persona.vibe_description, 400, 420 + persona.persona_traits.length * 35, 680, 22)}
  
  <!-- Fictional Schedule -->
  <text x="400" y="${560 + persona.persona_traits.length * 35}" font-family="Georgia, serif" font-size="24" fill="#ffffff" text-anchor="middle" font-weight="bold">
    ✦ A Day in the Life ✦
  </text>
  
  ${Object.entries(persona.fictional_schedule).map(([time, activity], i) => `
  <text x="100" y="${610 + persona.persona_traits.length * 35 + i * 60}" font-family="Georgia, serif" font-size="16" fill="#ffffff" opacity="0.9" font-weight="bold">
    ${time.charAt(0).toUpperCase() + time.slice(1)}:
  </text>
  ${wrapText(activity, 100, 630 + persona.persona_traits.length * 35 + i * 60, 600, 16)}
  `).join('')}
  
  <!-- Keywords -->
  <text x="400" y="${850 + persona.persona_traits.length * 35}" font-family="Georgia, serif" font-size="20" fill="#ffffff" text-anchor="middle" opacity="0.8">
    ${persona.aesthetic_keywords.slice(0, 5).join(' • ')}
  </text>
  
  <!-- Playlist -->
  <text x="400" y="1050" font-family="Georgia, serif" font-size="18" fill="#ffffff" text-anchor="middle" opacity="0.9">
    ♪ ${escapeXml(persona.spotify_playlist)} ♪
  </text>
  
  <!-- Footer -->
  <text x="400" y="1130" font-family="Georgia, serif" font-size="16" fill="#ffffff" text-anchor="middle" opacity="0.7">
    🌸 Generated by Muse.me 🌸
  </text>
</svg>`;

  return svg;
}

function escapeXml(text) {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function wrapText(text, x, y, maxWidth, fontSize) {
  const words = text.split(' ');
  const lines = [];
  let currentLine = '';
  const maxCharsPerLine = Math.floor(maxWidth / (fontSize * 0.5));
  
  words.forEach(word => {
    const testLine = currentLine + (currentLine ? ' ' : '') + word;
    if (testLine.length <= maxCharsPerLine) {
      currentLine = testLine;
    } else {
      if (currentLine) lines.push(currentLine);
      currentLine = word;
    }
  });
  if (currentLine) lines.push(currentLine);
  
  return lines.map((line, i) => `
  <text x="${x}" y="${y + i * (fontSize + 8)}" font-family="Arial, sans-serif" font-size="${fontSize}" fill="#ffffff" opacity="0.9">
    ${escapeXml(line)}
  </text>
  `).join('');
}
